=== Maxituz/maxituz.github.io/MaxMartínezAltimira_JSON/schema_comanda.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://exemple.cat/schema/producte.json",
  "title": "Comanda",
  "description": "Esquema de comanda de la botiga GameVault",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^GV-\\d{6}$"
    },
    "data": {
      "type": "string",
      "format": "date-time",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$"
    },
    "usuari": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "minimum": 1
        },
        "username": {
          "type": "string",
          "minimum": 3,
          "maximum": 20
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "pais": {
          "type": "string",
          "maximum": 3,
          "pattern": "^[A-Z]{3}$"
        }
      },
      "required": ["id", "username", "email", "pais"]
    },
    "jocs": {
      "type": "array",
      "minItems": 1,
      "properties": {
        "id": {
          "type": "integer",
          "minimum": 1
        },
        "titol": {
          "type": "string",
          "maximum": 120
        },
        "plataforma": {
          "type": "string",
          "enum": ["Windows", "Mac", "Linux", "Steam Deck"]
        },
        "preu": {
          "type": "number",
          "minimum": 0
        },
        "dlc": {
          "type": "boolean"
        }
      },
      "required": ["id", "titol", "plataforma", "preu"]
    },
    "pagament": {
      "type": "object",
      "properties": {
        "metode": {
          "type": "string",
          "enum": ["targeta", "paypal", "bizum", "crypto"]
        },
        "completat": {
          "type": "boolean"
        }
      },
      "required": ["metode", "completat"]
    },
    "total": {
      "type": "number",
      "minimum": 0
    }
  },
  "required": ["id", "data", "usuari", "jocs", "pagament", "total"],
  "additionalProperties": false
}

=== Maxituz/maxituz.github.io/MaxMartínezAltimira_JSON/comanda_GV.json
{
  "$schema": "./schema_comanda.json",
  "id": "GV-070907",
  "data": "2026-05-11T15:04:00Z",
  "usuari": {
    "id": 4,
    "username": "Max",
    "email": "max_martinezaltimira@iescarlesvallbonca.cat",
    "pais": "ESP"
  },
  "jocs": [
    {
      "id": 2,
      "titol": "Minecraft",
      "plataforma": "Windows",
      "preu": 29.99,
      "dlc": false
    },
    {
      "id": 40,
      "titol": "Factorio",
      "plataforma": "Windows",
      "preu": 39.99,
      "dlc": false
    },
    {
      "id": 55,
      "titol": "Pragmata",
      "plataforma": "Windows",
      "preu": 45,
      "dlc": false
    },
    {
      "id": 41,
      "titol": "Factorio: Space Age",
      "plataforma": "Windows",
      "preu": 29.99,
      "dlc": true
    }
  ],
  "pagament": {
    "metode": "paypal",
    "completat": true
  },
  "total": 144.97
}
