=== Maxituz/maxituz.github.io/XML/comanda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="comanda">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="proveidor" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nom" minOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="50" ></xs:maxLength>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="cif" minOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                      <xs:length value="9"></xs:length>
                    <xs:pattern value="[a-zA-Z].{8}"></xs:pattern>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="email" minOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:string"></xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="client" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nom" minOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="50"></xs:maxLength>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="cif" minOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[a-zA-Z].{8}"></xs:pattern>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="email" minOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="telefon" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:positiveInteger">
                    <xs:pattern value="[6-9][0-9]{8}"></xs:pattern>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="productes" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="producte" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nom" minOccurs="1">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="100"></xs:maxLength>
                        </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="categoria" minOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Processadors">
                    </xs:enumeration>
                    <xs:enumeration value="Memòria"></xs:enumeration>
                    <xs:enumeration value="Emmagatzematge"></xs:enumeration>
                    <xs:enumeration value="Xarxa"></xs:enumeration>
                    <xs:enumeration value="Perifèrics"></xs:enumeration>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="quantitat" minOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:positiveInteger">
                    <xs:minInclusive value="1"></xs:minInclusive>
                    <xs:maxInclusive value="500"></xs:maxInclusive>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="preu_unitat" minOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:minInclusive value="0.01"></xs:minInclusive>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
                  </xs:sequence>
                    <xs:attribute name="ref" type="xs:string" use="required"></xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>

      <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="data" type="xs:date" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Maxituz/maxituz.github.io/MaxMartínezAltimira_XML/comanda_TechCAT0001_corregit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Encara que sigui un int, el id ha d'estar entre cometes, a part el format de data ha de ser YYYY-MM-DD -->
<!-- <comanda id=1042 data="15-11-2024" -->
<comanda id="1042" data="2024-11-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="comanda.xsd">

  <proveidor>
    <nom>ElectroSupply SL</nom>
    <cif>B12345678</cif>
    <email>vendes@electrosupply.cat</email>
  </proveidor>

  <client>
    <nom>TechDist SA</nom>
    <!-- L'últim caràcter ha de ser un número -->
    <!-- <cif>A98765432X</cif> -->
    <cif>A98765432</cif>
    <email>compres@techdist.cat</email>
    <!-- El telèfon no pot tenir espais -->
    <!-- <telefon>934 567 890</telefon>-->
    <telefon>938421392</telefon>
  </client>

  <productes>
    <producte ref="CPU-I7-14">
      <nom>Intel Core i7-14700K</nom>
      <categoria>Processadors</categoria>
      <quantitat>10</quantitat>
      <preu_unitat>389.99</preu_unitat>
    </producte>
    <producte ref="RAM-DDR5-32">
      <nom>Kingston Fury Beast DDR5 32GB</nom>
      <!-- La categoria RAM no és vàlida -->
      <!-- <categoria>RAM</categoria> -->
      <categoria>Memòria</categoria>
      <!-- La quantitat ha de ser mínim de 1 -->
      <!-- <quantitat>0</quantitat> -->
      <quantitat>1</quantitat>
      <preu_unitat>129.99</preu_unitat>
    </producte>
    <producte ref="SSD-NVMe-1T">
      <nom>Samsung 990 Pro 1TB</nom>
      <categoria>Emmagatzematge</categoria>
      <quantitat>25</quantitat>
      <!-- El preu ha de ser positiu -->
      <!-- <preu_unitat>-89.99</preu_unitat> -->
      <preu_unitat>89.99</preu_unitat>
    <!-- No s'ha tancat correctament producte -->
    <!-- <producte> -->
    </producte>
  </productes>
</comanda>
